# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Moein Blog"
weight = 1

[fa]
languageName = "Persian"
languagedirection = "rtl"
title = "معین بلاگ"
weight = 1
